export const BINDINGS: ReadonlyArray<readonly [string, string]> = [
  ['↓ / j', 'Next tweet'],
  ['↑ / k', 'Previous tweet'],
  ['→', 'Open thread'],
  ['← / Esc', 'Back'],
  ['Home / gg', 'First tweet'],
  ['End / G', 'Last tweet'],
  ['Space', 'Expand truncated post (Mostrar mais / Show more)'],
  ['Space', 'Page down (when focused post is not truncated)'],
  ['⇧Space', 'Page up'],
  ['t', 'Translate focused post'],
  ['o → 1..9', 'Open link / media in active post'],
  ['r', 'Reload page'],
  ['.', 'Load new posts ("Mostrar N posts")'],
  ['1 / 2', 'For You / Following (Home)'],
  ['h', 'Go to Home'],
  ['e', 'Go to Explorer and focus search'],
  ['?', 'Toggle help'],
];
